# Generated by Django 3.2.10 on 2021-12-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeeprofile_saved_jobs'),
        ('job', '0003_interview'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notifications_type',
        ),
        migrations.CreateModel(
            name='EmployeeNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.interview')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('sender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employerprofile')),
            ],
        ),
    ]
