# Generated by Django 3.2.10 on 2021-12-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeeprofile_saved_jobs'),
        ('job', '0003_interview'),
        ('notifications', '0002_auto_20211225_0318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeNotifications',
            new_name='EmployeeNotification',
        ),
    ]
