# Generated by Django 3.2.9 on 2021-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20211222_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='extra_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='namejob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
