# Generated by Django 3.2.10 on 2021-12-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_employeenotifications_employeenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
