# Generated by Django 3.2.10 on 2021-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='discussion title', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
