# Generated by Django 3.2.10 on 2021-12-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='place',
        ),
        migrations.AddField(
            model_name='info',
            name='message',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
