# Generated by Django 3.2.10 on 2021-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
