# Generated by Django 3.2.10 on 2021-12-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, null=True, to='job.Job'),
        ),
    ]
