# Generated by Django 3.2.10 on 2021-12-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_is_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
