# Generated by Django 3.2.10 on 2021-12-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211216_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='company_number',
            new_name='phone_number',
        ),
    ]
