# Generated by Django 3.2.10 on 2021-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_interview'),
        ('accounts', '0003_alter_employeeprofile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='job.Job'),
        ),
    ]
