# Generated by Django 3.2.10 on 2021-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20211211_0952'),
        ('accounts', '0006_alter_profile_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='job.Job'),
        ),
    ]
