# Generated by Django 3.2.10 on 2021-12-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211220_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='full_name',
        ),
    ]
