# Generated by Django 3.2.10 on 2021-12-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_name_application_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experince',
            new_name='experience',
        ),
    ]
