# Generated by Django 3.2.10 on 2021-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20211211_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
