# Generated by Django 3.2.10 on 2021-12-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20211220_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='created',
        ),
    ]
