# Generated by Django 3.2.10 on 2021-12-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20211220_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experince',
            new_name='experience',
        ),
    ]
