//auth dispatch states
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const DELETE_USER_SUCCESS = "AUTHENTICATED_SUCCESS";
export const DELETE_USER_FAIL = "AUTHENTICATED_FAIL";

//profile dispatch states
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

//posts dispatch states
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAIL = "LOAD_POSTS_FAIL";
export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS";
export const LOAD_POST_FAIL = "LOAD_POST_FAIL";

//job dispatch states
export const LOAD_JOBS_SUCCESS = "LOAD_JOBS_SUCCESS";
export const LOAD_JOBS_FAIL = "LOAD_JOBS_FAIL";
export const LOAD_JOB_SUCCESS = "LOAD_JOB_SUCCESS";
export const LOAD_JOB_FAIL = "LOAD_JOB_FAIL";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_FAIL = "ADD_JOB_FAIL";

//contact us states
export const SEND_INFO_SUCCESS = "SEND_INFO_SUCCESS";
export const SEND_INFO_FAIL = "SEND_INFO_FAIL";

//category states
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CATEGORIES_FAIL = "LOAD_CATEGORIES_FAIL";

//job application states
export const JOB_APPLICATION_SUCCESS = "JOB_APPLICATION_SUCCESS";
export const JOB_APPLICATION_FAIL = "JOB_APPLICATION_FAIL";

//job application reject
export const APPLICATION_REJECT_SUCCESS = "APPLICATION_REJECT_SUCCESS";
export const APPLICATION_REJECT_FAIL = "APPLICATION_REJECT_FAIL";

//jobs filter states
export const JOBS_FILTER_SUCCESS = "JOBS_FILTER_SUCCESS";
export const JOBS_FILTER_FAIL = "JOBS_FILTER_FAIL";

//jobs search states
export const JOBS_SEARCH_SUCCESS = "JOBS_SEARCH_SUCCESS";
export const JOBS_SEARCH_FAIL = "JOBS_SEARCH_FAIL";

// apply job states
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";

// setup interview states
export const SETUP_INTERVIEW_SUCCESS = "SETUP_INTERVIEW_SUCCESS";
export const SETUP_INTERVIEW_FAIL = "SETUP_INTERVIEW_FAIL";
